version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.2-stretch-browsers
    steps:
      - checkout
      - run: 
          name: Install Testing Env
          command: pip install pytest
      - run:
          name: Run test Suite
          command: python -m pytest
