version: 2
jobs:
  build:
    docker:
      - image: python:3.8-r
    steps:
      - checkout
      - run: 
          name: Install Testing Env
          command: pip install pytest
      - run:
          name: Run test Suite
          command: python -m pytest
