version: 2
jobs:
  build:
    docker:
      - image: python:3
    steps:
      - checkout
      - run: 
          name: Install Testing Env
          command: pip install pytest
      - run:
          name: Install Test Reporter
          command: pip install codecov
      - run:
          name: Run test Suite
          command: pytest --cov=./
      - store_test_results:
                path: test-reports
      - store_artifacts:
                path: test-reports   
      - run:
          name: Report Tests
          command: codecov